services:
  main:
    container_name: main
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    command:
      - sh
      - -c
      - |
        npx prisma migrate dev --name init && npm run start:dev
    depends_on:
      - postgresql
    restart: always
  postgresql:
    image: postgres
    container_name: db-postgres
    ports:
      - '5432:5432'
    env_file:
      - .env
    environment:
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
